<script setup lang="ts">
const props = defineProps<{
  html: string;
  styles?: string[];
  syntaxes?: string[];
}>();
const root = ref<HTMLElement>();
const remoteFeatures = useRuntimeConfig().public.remoteFeatures;
const { t } = useCopy();
let generation = 0;
let disposers: (() => void)[] = [];
function cleanup() {
  disposers.forEach((dispose) => dispose());
  disposers = [];
}
useHead(() => ({
  link: (props.styles || []).map((href) => ({
    key: `markdown:${href}`,
    rel: "stylesheet",
    href,
  })),
}));
async function enhance() {
  cleanup();
  const current = ++generation;
  await nextTick();
  const el = root.value;
  if (!el) return;
  for (const scrollable of el.querySelectorAll<HTMLElement>(".katex-display")) {
    scrollable.tabIndex = 0;
  }
  for (const pre of el.querySelectorAll("pre")) {
    if (pre.closest("[data-mermaid]")) continue;
    if (
      pre.closest(".not-prose") &&
      !pre.closest(".m3-code-tree, .m3-option-group")
    )
      continue;
    const host = pre.closest(".frame") || pre;
    if (host.querySelector("[data-copy-code]")) continue;
    const button = document.createElement("button");
    button.type = "button";
    button.dataset.copyCode = "";
    button.textContent = t("copyCode");
    button.setAttribute("aria-label", t("copyCode"));
    button.className = "article-code-copy";
    button.addEventListener("click", async () => {
      try {
        const lines = pre.querySelectorAll(".ec-line > .code");
        await navigator.clipboard.writeText(
          lines.length
            ? [...lines].map((line) => line.textContent || "").join("\n")
            : pre.querySelector("code")?.textContent || "",
        );
        button.textContent = t("copySuccess");
      } catch {
        button.textContent = t("copyFailed");
      }
    });
    host.append(button);
    disposers.push(() => button.remove());
  }

  if (
    el.querySelector(
      "[data-audio-reader],[data-youtube],[data-bilibili],[data-acfun],video",
    )
  ) {
    const { initMedia } = await import("~/utils/markdown/media");
    if (current !== generation) return;
    disposers.push(initMedia(el, remoteFeatures));
  }
  if (remoteFeatures && el.querySelector("[data-github-repo]")) {
    const { initGithub } = await import("~/utils/markdown/github");
    if (current !== generation) return;
    disposers.push(initGithub(el));
  }
  if (el.querySelector("abbr[data-abbreviation-expansion]")) {
    const { initAbbreviations } =
      await import("~/utils/markdown/abbreviations");
    if (current !== generation) return;
    disposers.push(initAbbreviations(el));
  }
  if (el.querySelector(".m3-option-group")) {
    const { initOptionGroups } = await import("~/utils/markdown/option-groups");
    if (current !== generation) return;
    disposers.push(initOptionGroups(el));
  }
  if (el.querySelector(".m3-code-tree")) {
    const { initTrees } = await import("~/utils/markdown/trees");
    if (current !== generation) return;
    disposers.push(initTrees(el));
  }
  if (props.syntaxes?.includes("mermaid")) {
    const { default: mermaid } = await import("mermaid");
    if (current !== generation) return;
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: "strict",
      theme: document.documentElement.classList.contains("dark")
        ? "dark"
        : "default",
    });
    for (const [i, figure] of [
      ...el.querySelectorAll<HTMLElement>("[data-mermaid]"),
    ].entries()) {
      const source = figure.querySelector("pre")?.textContent || "";
      figure.dataset.mermaidState = "loading";
      try {
        const { svg } = await mermaid.render(`diagram-${current}-${i}`, source);
        if (current !== generation) return;
        const target = figure.querySelector(".markdown-mermaid__diagram");
        if (target) {
          target.innerHTML = svg;
          // The shared stylesheet owns diagram/source visibility through this state.
          figure.dataset.mermaidState = "ready";
        }
      } catch {
        if (current !== generation) return;
        figure.dataset.mermaidState = "error";
      }
    }
  }
}
function activate(event: MouseEvent) {
  const target = event.target as HTMLElement;
  const spoiler = target.closest<HTMLElement>("[data-spoiler]");
  if (spoiler) {
    spoiler.classList.toggle("revealed");
    spoiler.setAttribute(
      "aria-expanded",
      String(spoiler.classList.contains("revealed")),
    );
  }
}
onMounted(enhance);
watch(() => props.html, enhance);
onBeforeUnmount(() => {
  generation++;
  cleanup();
});
</script>
<template>
  <!-- HTML is generated by the shared sanitizing content compiler. -->
  <!-- eslint-disable vue/no-v-html -- shared compiler sanitizes source HTML; DOMPurify sanitizes local preview -->
  <div
    ref="root"
    class="prose custom-md"
    @click="activate"
    v-html="html"
  />
</template>
