<script setup lang="ts">
const props = defineProps<{
  html: string;
  styles?: string[];
  syntaxes?: string[];
}>();
const root = ref<HTMLElement>();
const remoteFeatures = useRuntimeConfig().public.remoteFeatures;
const { t } = useCopy();
let generation = 0;
let disposers: (() => void)[] = [];
function cleanup() {
  disposers.forEach((dispose) => dispose());
  disposers = [];
}
useHead(() => ({
  link: (props.styles || []).map((href) => ({
    key: `markdown:${href}`,
    rel: "stylesheet",
    href,
  })),
}));
async function enhance() {
  cleanup();
  const current = ++generation;
  await nextTick();
  const el = root.value;
  if (!el) return;
  for (const pre of el.querySelectorAll("pre")) {
    if (pre.closest("[data-mermaid]") || pre.querySelector("[data-copy-code]"))
      continue;
    const button = document.createElement("button");
    button.type = "button";
    button.dataset.copyCode = "";
    button.textContent = t("copyCode");
    button.addEventListener("click", async () => {
      try {
        await navigator.clipboard.writeText(
          pre.querySelector("code")?.textContent || "",
        );
        button.textContent = t("copySuccess");
      } catch {
        button.textContent = t("copyFailed");
      }
    });
    pre.append(button);
  }

  if (
    el.querySelector(
      "[data-audio-reader],[data-youtube],[data-bilibili],[data-acfun],video",
    )
  ) {
    const { initMedia } = await import("~/utils/markdown/media");
    if (current !== generation) return;
    disposers.push(initMedia(el, remoteFeatures));
  }
  if (remoteFeatures && el.querySelector("[data-github-repo]")) {
    const { initGithub } = await import("~/utils/markdown/github");
    if (current !== generation) return;
    disposers.push(initGithub(el));
  }
  if (el.querySelector(".m3-code-tree")) {
    const { initTrees } = await import("~/utils/markdown/trees");
    if (current !== generation) return;
    disposers.push(initTrees(el));
  }
  if (props.syntaxes?.includes("mermaid")) {
    const { default: mermaid } = await import("mermaid");
    if (current !== generation) return;
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: "strict",
      theme: document.documentElement.classList.contains("dark")
        ? "dark"
        : "default",
    });
    for (const [i, figure] of [
      ...el.querySelectorAll<HTMLElement>("[data-mermaid]"),
    ].entries()) {
      const source = figure.querySelector("pre")?.textContent || "";
      try {
        const { svg } = await mermaid.render(`diagram-${current}-${i}`, source);
        if (current !== generation) return;
        const target = figure.querySelector(".markdown-mermaid__diagram");
        if (target) {
          target.innerHTML = svg;
          const fallback = figure.querySelector("pre");
          if (fallback) fallback.hidden = true;
        }
      } catch {
        /* readable source remains */
      }
    }
  }
}
function activate(event: MouseEvent) {
  const target = event.target as HTMLElement;
  const tab = target.closest<HTMLElement>("[role=tab]");
  if (tab && root.value?.contains(tab)) {
    const group = tab.closest("[role=tablist]");
    group?.querySelectorAll("[role=tab]").forEach((t) => {
      const selected = t === tab;
      t.setAttribute("aria-selected", String(selected));
      t.setAttribute("tabindex", selected ? "0" : "-1");
      const panel = root.value?.querySelector<HTMLElement>(
        `[id="${CSS.escape(t.getAttribute("aria-controls") || "")}"]`,
      );
      if (panel) panel.hidden = !selected;
    });
  }
  const spoiler = target.closest<HTMLElement>("[data-spoiler]");
  if (spoiler) {
    spoiler.classList.toggle("revealed");
    spoiler.setAttribute(
      "aria-expanded",
      String(spoiler.classList.contains("revealed")),
    );
  }
}
function keyboard(event: KeyboardEvent) {
  const target = event.target as HTMLElement;
  if (
    target.getAttribute("role") !== "tab" ||
    !["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)
  )
    return;
  const tabs = [
    ...(target
      .closest("[role=tablist]")
      ?.querySelectorAll<HTMLElement>("[role=tab]") || []),
  ];
  const index = tabs.indexOf(target);
  const next =
    event.key === "Home"
      ? 0
      : event.key === "End"
        ? tabs.length - 1
        : (index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) %
          tabs.length;
  event.preventDefault();
  tabs[next]?.focus();
  tabs[next]?.click();
}
onMounted(enhance);
watch(() => props.html, enhance);
onBeforeUnmount(() => {
  generation++;
  cleanup();
});
</script>
<template>
  <!-- HTML is generated by the shared sanitizing content compiler. -->
  <!-- eslint-disable vue/no-v-html -- shared compiler sanitizes source HTML; DOMPurify sanitizes local preview -->
  <div
    ref="root"
    class="prose custom-md"
    @click="activate"
    @keydown="keyboard"
    v-html="html"
  />
</template>
